# Generated by Django 4.1.5 on 2023-02-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='RATING')),
                ('comment', models.TextField(max_length=300, verbose_name='COMMENT')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
            ],
        ),
    ]
