# Generated by Django 4.1.5 on 2023-02-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Rate',
        ),
    ]
