# Generated by Django 4.1.5 on 2023-02-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='CATEGORY')),
                ('address', models.CharField(max_length=100, verbose_name='ADDRESS')),
                ('star', models.FloatField(blank=True, null=True, verbose_name='star')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='COMMENT')),
                ('naver_services', models.CharField(blank=True, max_length=150, null=True, verbose_name='SERVICES')),
                ('station', models.CharField(blank=True, max_length=20, null=True, verbose_name='STATION')),
                ('out', models.CharField(blank=True, max_length=20, null=True, verbose_name='OUT')),
                ('meter', models.FloatField(blank=True, null=True, verbose_name='METER')),
                ('lines', models.CharField(blank=True, max_length=100, null=True, verbose_name='LINES')),
                ('walking_time', models.FloatField(blank=True, null=True, verbose_name='WALKING_TIME')),
            ],
        ),
    ]
