# Generated by Django 4.1.5 on 2023-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='NAME'),
        ),
    ]
