# Generated by Django 4.1.5 on 2023-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stores_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='CONTENT')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
            ],
        ),
        migrations.AlterField(
            model_name='stores',
            name='star',
            field=models.FloatField(blank=True, null=True, verbose_name='STAR'),
        ),
    ]
