# Generated by Django 4.1.5 on 2023-02-08 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_searchwithfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchwithfeedback',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='CREATE_DATE'),
        ),
    ]
